### ISSUE TITLE
Meny-sidebaren?

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#10]
Hvis denne siden skal ligne på nettsiden vår burde den inneholde menyen i sidebaren.
Men vil vi egentlig det? Noen undersider har den ikke.
Og hvis den bor der, hva skal det linkes til? Antar Artskart (ekstern) og doi.org doi for denne hadde gitt mening?

Trenger innspill! @tovelitovela @olsoybakk

**Comment by tovelitovela** [comment]
Tilbake til Artskart kunne gitt mening!

**Comment by olsoybakk** [comment]
Husk at i framtiden vil vi ha en DOI for alt mulig. F.eks. for hver taxon. Dvs Artskart er ikke alltid kilden.

**Comment by olsoybakk** [comment]
..men da peker det mot takson-sidene. Stryk siste melding 😄

**Comment by helemork** [comment]
Når den dagen kommer, @olsoybakk, har vi litt hardkoda ting å fjerne her og der. Sånn som... artskartlenke osv. VI har mye som nå er direkte artskartrelatert. Så ser for meg at den dagen vi introduserer andre doier er det mer enn én tilpasning å fikse :) Sannsynligvis store deler av innholdet vil jeg tro.
