### ISSUE TITLE
Ymse om rekkefølger og utheving

### ISSUE THREAD

**Issue by tovelitovela** [Artsdatabanken/doi-frontend#13]
- [x] Flytte "Last ned" opp over "Kartinformasjon". Den er noe av det viktigste på siden og man forstår fortere hva slags side man er på om man ser den helt fra starten.
- [x] Flytte knappen "Samme utvalg med oppdaterte data" helt nederst på siden
- [x] Overskriftene "KArtinformasjon" og "Kartutsnitt" - er det nødvendig med begge?

**Comment by tovelitovela** [comment]
Vet ikke hvorfor jeg gjorde dette til en tasklist... det er jo forslag. Må ikke gjøres! :D

**Comment by helemork** [comment]
Helt nederst på storskjerm er ikke helt nederst på mobil må sies, men tenker det går greit :)

**Comment by helemork** [comment]
Grunnen til at det er to overskrifter der er fordi det tidvis er en annen der også for områder. Kan sløyfe den likevel da.

**Comment by helemork** [comment]
Forstod ikke øverste punkt? Mener du progressbaren som er når eksporten ikke er klar?

**Comment by tovelitovela** [comment]
Ja, jeg mener progressbaren. Men jeg lurer på om jeg har sett på en rar side. Den skal forsvinne når nedlastningen er over?

**Comment by helemork** [comment]
Hvis du er inne på siden når den er over, forblir den utfylt. (så du skal se den er ferdig)
Hvis du refresher, elller går inn på en ferdig side derimot er den borte :)
Ikke bra?

**Comment by tovelitovela** [comment]
Det høres slett ikke dumt ut det! Men stylingen må skille seg fra underoverskrifter og avsnitt som er fast på siden.

**Comment by helemork** [comment]
Men det er jo en underoverskrift og en seksjon/paragraf med innhold.
Hvis det ikke skal være det... hva skal det være da?
Jeg er litt ute av stand til å komme på andre måter å fremstille det på uten noen hint eller forslag.
