### ISSUE TITLE
Opprydding av DOI landingpage

### ISSUE THREAD

**Issue by olsoybakk** [Artsdatabanken/doi-frontend#23]
DOI Landingpage har blitt veldig bra nå. En får inntrykk av at en er hos Artsdatabanken 👍 

@knutanders og @olsoybakk har sett litt på om vi har noe unødig info på siden:

- GUID er intern og bør ikke vises på start- og DOI-siden
- Eksporttype mangler (excel/csv), men dette skyldes nok at den falt ut fra bestilling av DOI i Artskart @olsoybakk fixer

Annet:
Hva er viktig og uviktig informasjon her?
![image](https://user-images.githubusercontent.com/10737686/115402361-a5718980-a1eb-11eb-8bc4-359e2cc76305.png)

**Comment by helemork** [comment]
Fjerner guid for nå, de andre vil jeg ha endelig konklusjon på før jeg tar bort/rører.
Jeg ville sagt det er nyttig å ha zip der, men kanskje der burde vært putta inn i nedlastningsknappen så de vet de laster ned en zip?

Api synes jeg er nyttig, men kanskje det burde vært vist som "se datasett som api" eller noe, og fremstilles på samme måte som artskartknappen/downloadknappen, evt. rett under med en tekst á la "gå til api versjon"

**Comment by helemork** [comment]
Denne er ikke lenger relevant med nyeste endringer i forbindelse med #32
