### ISSUE TITLE
Bildekilde

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#25]
Finne en god måte å sitere bildene på.

https://test.artsdatabanken.no/artskartwebapi2/api/raster/distribution?height=800&width=500&ScientificNameId=71898&layers=gebco,osm_blur,terrengmodell,svalbardterreng

**Comment by olsoybakk** [comment]
Da ble det sånn: _CoverageSource#<layer>|<name>|<url>_
_layer_ - navn på laget - dette trenger du ikke vise på siden
_name_ - Lesbart navn på leverandøren
_url_ - url til leverandør

Eksempel: https://doiapi.test.artsdatabanken.no/api/Doi/getDoiByGuid/cf811775-e99c-1c64-72a8-98eabd6c24a5

`    {`
`      "description": "CoverageSource#gebco|Norwegian Mapping Authority|http://www.kartverket.no/",`
`      "descriptionType": "TechnicalInfo",`
`      "lang": null`
`    },`
`    {`
`      "description": "CoverageSource#osm_blur|OpenStreetMap|https://www.openstreetmap.org/",`
`      "descriptionType": "TechnicalInfo",`
`      "lang": null`
`    },`
`    {`
`      "description": "CoverageSource#terrengmodell|Norwegian Mapping Authority|http://www.kartverket.no/",`
`      "descriptionType": "TechnicalInfo",`
`      "lang": null`
`    },`
`    {`
`      "description": "CoverageSource#svalbardterreng|Norwegian Mapping Authority|http://www.kartverket.no/",`
`      "descriptionType": "TechnicalInfo",`
`      "lang": null`
`    }`

**Comment by helemork** [comment]
Fikset
