### ISSUE TITLE
Få på plass lisens

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#29]
Lisens for datasettet, 
Datasettet er jo vårt, men kommer av underkilder som kan ha egen lisens. 
Vi bør ha en tydelig boks med hvilken lisens dette datasettet kommer under, samt lenke til hva det betyr.
Vi bør også i denne sammenheng ha en kontaktinformasjons-boks hvor brukere kan kontakte oss ved behov, f.eks om det ikke virker på noe vis.

**Comment by helemork** [comment]
@steinho skrev: Er usikker, men ville tippet at det må være likt med nedlasting fra gbif: CC BY-NC 4.0 siden det er blanding av enkeltposter fra datasett der den strengeste lisensen man kan setter er denne... F.eks: https://www.gbif.org/occurrence/download/0017997-190415153152247

**Comment by WouterKoch** [comment]
Her er det 3 nivåer som lisensieres, uavhengig av hverandre:
- Datasettet, som har sui generis databaserettigheter uavhengig av lisens/opphavsrett av hva det inneholder. Dette er altså lisensen som dekker den ikke-trivielle prosessen av å bestemme hva som innegår i et datasett og ikke. Her gir ikke annet enn CC BY så mye mening, det blir vanskelig å si hva som er et avledet verk av utvalget, for eksempel, eller at et bestemt utvalg av data kun kan brukes av ikke-kommersielle aktører, mens de samme dataene som et litt annet utvalg kan det.
- Datapunkter, altså informasjon om hva som ble observert hvor. Det er tvilsomt om slike rene fakta har opphavsrettigheter i det hele tatt, men siden vitenskapelig praksis uansett er sitering er det CC BY som gjelder,
- Bilder knyttet til funn. De kan være alt fra alle rettigheter forbeholdt til CC0. De har sin egen lisens, uavhengig av funnet eller datasettet.

Datasettet bør altså ha lisensen CC BY. GBIF tillater NC lisensiering for datapunkter, dette er et kompromiss mot de som vil være så restriktive som mulig. De viser den overordnete lisensen slik for å hindre at noen misforstår og tror at det gjelder innholdet, men i praksis har det ingen betydning.

I Artsdatabanken slipper vi dette siden CC BY er eneste mulighet for selve funnet, og har alltid vært det. Se https://artsdatabanken.no/Pages/233436?Key=1435226523 og https://www.artsobservasjoner.no/Home/TermsOfUse (punkt 9). Dermed er databaselisensen og datapunktlisensen allerede like ved å bruke CC BY. Vi slipper dermed å forklare at databaserettigheter og observasjonsrettigheter er to separate ting :)
