### ISSUE TITLE
Toppen på sida

### ISSUE THREAD

**Issue by tovelitovela** [Artsdatabanken/doi-frontend#34]
- [x] Underoverskrift skal stå som "DOI: 10.435.323......"
- [x] Knapp med "Last ned datasettet" flyttes tilbake fra høyremarg, rett under ingress
- [x] Siden trenger ingen venstremeny
- [x] Ingress: "Datasettet inneholder 75 observasjoner av xx, xx og xx, og er et øyeblikksbilde fra da datasettet ble opprettet." XX hentes fra filter på taksonomiske nivå gjort i artskart(bjørn, jerv, roseslekta, mårfamilien hva enn). Er det valgt fler enn tre taksoner droppes det og det får stå som i dag.

**Comment by tovelitovela** [comment]
@knutanders

**Comment by helemork** [comment]
Som sagt er det langt i fra alltid vi har arter i filteret, ofte kan filteret være et område eller polygon eller slikt. Er det likevel hensiktsmessig å ta det inn i ingress?

**Comment by tovelitovela** [comment]
Ja, det er såpass vanlig at folk interessert i spesifikke artsgrupper/arter at det er verdt å lage en fiks for i ingressen. Andre filter trenger du ikke tenke på her :)

**Comment by knutanders** [comment]
Enig med @tovelitovela her i at taxon som inngår i søket er litt annleis enn andre filter. Er kun dersom taxon blir brukt til å definere søket at vi ønsker taxon i ingressen.
