### ISSUE TITLE
Filinformasjon

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#4]
- [x] legg til eksporttype
- [x] link doi til seg selv, skjul url
Fjern:
- [x] Kildetype
- [x] url:
- [x] metadataVersion:
- [x] schemaVersion:
- [x] resourceTypeGeneral:
- [x] schemaOrg:
- [x] bibtex:
- [x] citeproc:
- [x] ris:

**Comment by olsoybakk** [comment]
Her er en med litt info:
[https://doi-fe.test.artsdatabanken.no/#cab81716-f7da-7e3a-5845-e9c44eea77bc](https://doi-fe.test.artsdatabanken.no/#cab81716-f7da-7e3a-5845-e9c44eea77bc)
