### ISSUE TITLE
Footer og Headerinnhold?

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#8]
Skal footeren ha samma innhold som hovedsiden?
Skal headeren?
MÅ også funke på mobil (gjør ikke det nå)

Hva tror dere, @tovelitovela og @olsoybakk

**Comment by helemork** [comment]
https://www.artsdatabanken.no/api/Content/224883
Her har @steinho gitt innholdet til menyen.
Kanskje, om vi er heldige, så finnes det også for footeren?

**Comment by tovelitovela** [comment]
Ja, jeg synes det skal være samme header og footer som på hovedsiden når vi går for et visuelt uttrykk som er så likt den. Alternativt måtte siden sett ut som en del av Artskart, og helt ærlig synes jeg ikke det høres ut som en drøm.. :)

**Comment by helemork** [comment]
Denne er nå påstartet (og fungerer), men har noen meget tydelige bugs. samt mangler litt på det visuelle.

Det mest tydelige problemet er rett og slett at den har feil lenke for eksterne applikasjoner. Det lette hadde jo vært å overkjøre dette api'et vårt, men da er det jo ikke sikkert ting blir likt om man skal endre på nettsiden. 
Inntil videre setter jeg den derfor på on hold til vi har en bedre plan.

**Comment by helemork** [comment]
Litt hjelp fra @Myrdrahl har latt oss spore opp footeren:
https://www.artsdatabanken.no/Pages/224885

**Comment by helemork** [comment]
Header komplett innhold og funksjonsmessig bortsett fra utseendet til språk-knappen. Hva som skal skje når man trykker der må tas stilling til.

Men feltet med engelsk strider imot universell utforming. SÅ skal jeg da bruke tid på å lage en kopi som også strider i mot, eller la den stå slik den er?

Egentlig burde den jo gi en engelsk variant av DENNE siden, som vi faktisk burde ha...?

## Forklaring:
Ettersom det er inne i  menyen og de andre menypunkdene gir dropdowns, er det misvisende at et menypunkt er en lenke til en annen side. Naturlig adferd ville vært at den og var en dropned som ga oss et valg mellom språk. Innser jo grunnen er at den bare har en lenke, men likevel, konsistent adferd. Den er også bare et flagg i ikon, hvorav flagget er skjult som en bakgrunn (derav ingen alt tekst, men ser ut som noen har slengt på en aria). Problemet med bare flagg, er at vi antar alle våre brukere forstår at det er det engelske flagget, og at egentlig burde vi vist det norske siden vi per nå er på den norske, og med en droppned til det andre alternativet. nå ser det ut som man er på den engelske versjonen. Forøvrig - skriver vi alltid britisk og ikke amerikansk?

**Comment by tovelitovela** [comment]
Her er det beste å droppe menypunktet "English"!
