### ISSUE TITLE
Overskrift

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/doi-frontend#9]
Det er litt snedig at siden heter "DOI landingsside". Jeg tenker det er mer hensiktsmessig at den heter noe mer fornuftig, men har ingen gode forslag. Burde doi'en inn der? Det vil bli rotete.
 
Hvis ikke doi'en skal i tittelen tenker jeg den på små skjermer må høyere opp, eller legges som en undertittel, siden den nå bor i sidebar-boksen som nå er langt, langt nede.

**Comment by tovelitovela** [comment]
Kunne det hett noe mer i gata "Artskart DOI" ?

**Comment by tovelitovela** [comment]
Eller! "Datasett DOI"? 

Og så må vi ha det forklart en plass (boks i siden?) at DOI står for Digital object identifyer og er en ID for et elektronisk dokument og blabla

**Comment by tovelitovela** [comment]
Og enig i at selve DOIen må inn i eller rett under overskrifta

**Comment by helemork** [comment]
Har vi noen sider med eksempler på undertitler? Jeg fant ingen. Kan om ikke annet putte det i ingressen

**Comment by tovelitovela** [comment]
https://beta.artsdatabanken.no/Pages/234877
https://beta.artsdatabanken.no/Pages/244937/Kartleggingsenheter_br__small_maalestokk_1_5000__small_
https://beta.artsdatabanken.no/Pages/305727/Parasittiske_krepsdyr_br__small_12-21__small_

Her er et par eksempler på en stil vi har kjørt, men dette er ikke bra, blant annet pga urlen…. :D Men om du får til noe i samme gata utseendemessig så bryter det ikke med praksis i alle fall.

**Comment by tovelitovela** [comment]
Ups, vet ikke hvorfor jeg la ved lenker til beta... Det var ikke poenget i alle fall :D
